name: Android App Build

on:
  workflow_dispatch:
    inputs:
      JDK:
        description: 'JDK'
        required: true
        default: '21'
      Project:
        description: '項目地址'
        required: true
        default: 'https://github.com/Tonyha7/Dreamland'
      ProjectName:
        description: '項目名称'
        required: true
        default: 'Dreamland'
      BCommand:
        description: '構建命令'
        required: true
        default: 'gradlew assembleMagiskDebug assembleMagiskRelease'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 準備
        uses: actions/checkout@v3
      
      - name: 安裝JDK環境
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ github.event.inputs.JDK }}
          

      - name: Clone源碼
        run: |
          git clone ${{ github.event.inputs.Project }} ${{ github.event.inputs.ProjectName }}
          ls -a
          cd ./${{ github.event.inputs.ProjectName }}/
          ls
          
      - name: 授予gradlew執行權限
        run: chmod +x ./${{ github.event.inputs.ProjectName }}/gradlew
        
      - name: 構建Release
        run: |
          cd ./${{ github.event.inputs.ProjectName }}/
          ./${{ github.event.inputs.BCommand }}
          
      - name: 上傳Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.ProjectName }}_Build
          path: ${{ github.event.inputs.ProjectName }}/app/build/outputs/magisk/

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ${{ github.event.inputs.ProjectName }}/app/build/outputs/magisk/*
          name: APK_${{ github.run_id }}
          tag_name: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
