name: 构建

on:
  workflow_dispatch:
    inputs:
      JDK:
        description: 'JDK'
        required: true
        default: '11'
      BCommand:
        description: '構建命令'
        required: true
        default: 'gradlew clean app:assembleRelease'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 準備
        uses: actions/checkout@v3
      
      - name: 安裝JDK環境
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ github.event.inputs.JDK }}
          
      - name: Android SDK
        uses: android-actions/setup-android@v2
          
      - name: NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          
      - name: 跑
        run: |
          git clone https://github.com/ljlVink/LinspirerDemo.git
          cd ./LinspirerDemo/LinspirerDemo-master/
          chmod 777 gradlew
          ./${{ github.event.inputs.BCommand }}
