name: 构建

on:
  workflow_dispatch:
    inputs:
      JDK:
        description: 'JDK'
        required: true
        default: '11'
      BCommand:
        description: '構建命令'
        required: true
        default: 'gradlew clean app:assembleRelease'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 準備
        uses: actions/checkout@v3
        
      - name: SSH Keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: |
                ${{ secrets.SSH_PRIVATE_KEY }}
                
      - name: 安裝JDK環境
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ github.event.inputs.JDK }}
          
      - name: Android SDK
        uses: android-actions/setup-android@v2
          
      - name: NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
          
      - name: 跑
        run: |
          git config --global user.name "Tonyha7"
          git config --global user.email "tonyha7@outlook.jp"
          git clone git@github.com:ljlVink/LinspirerDemo.git
          cd ./LinspirerDemo
          git submodule update --init
          cd ./LinspirerDemo-master
          mkdir libs
          cp ./hackmdm/libs/* ./libs
          cd ./libs/
          ls
          cd ..
          chmod 777 gradlew
          ./${{ github.event.inputs.BCommand }}

      - name: 上傳Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LSPDemo_Build
          path: ./LinspirerDemo/LinspirerDemo-master/app/build/outputs/apk/
