name: BML

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: 安装python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: clone
        run: |
          git clone https://github.com/Gamepiaynmo/BallanceModLoader BML
        
      - name: build
        run: |
          cd BML
          tree
          MSBuild ./BML.sln /p:Configuration=Release /property:Platform=x86 /p:UsePrecompiledHeader=false /m
        continue-on-error: true

      - name: tree
        run: |
          cd BML
          tree
