name: 构建nmmp

on:
  workflow_dispatch:
    inputs:
      JDK:
        description: 'JDK'
        required: true
        default: '8'
      APK:
        description: 'APK直链'
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 準備
        uses: actions/checkout@v3
                
      - name: 安裝JDK環境
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ github.event.inputs.JDK }}
          
      - name: Android SDK
        uses: android-actions/setup-android@v2
          
      - name: NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          
      - name: 安裝Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: 安裝CMAKE
        uses: lukka/get-cmake@latest
        
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 6
          
      - name: 跑
        run: |
          df -h
          git clone https://github.com/maoabc/nmmp.git
          cd ./nmmp/nmm-protect
          chmod 777 gradlew
          ./gradlew arsc:build
          ./gradlew build
          
      - name: 上傳Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nmmp_Build
          path: ./nmmp/nmm-protect/build/libs
