name: Nuitka

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: 安装python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          architecture: 'x64'

      - name: 安装requirements.txt
        run: pip install -r requirements.txt

      - nName: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: test
          onefile: true

      - name: 打包单文件exe并移动至根目录
        run: |
          move ./build/test.exe ./
          
      - name: 自动生成更新文档
        run: write-output "CHANGELOG:${{ github.event.head_commit.message }}" | out-file -filepath ./CHANGELOG.txt
        
      - name: 上传Release
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "./test.exe"
          tag: ver-${{ github.sha }}
          bodyFile: "./CHANGELOG.txt"
          token: ${{ secrets.GITHUB_TOKEN }}