name: Patch Generator

on:
  workflow_dispatch:
    inputs:
      URL:
        required: true
      COMMIT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git clone ${{ github.event.inputs.URL }} temp

      - name: Gen Patch
        run: |
          cd temp
          git format-patch ${{ github.event.inputs.COMMIT }}
          mkdir upload
          cp *.patch upload
          cd upload
          zip -r patch.zip ./*

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            temp/upload/patch.zip
            temp/*.patch
          name: Patch_${{ github.run_id }}
          tag_name: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
