name: srps

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'git url'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 準備
        uses: actions/checkout@v3
      
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Build
        run: |
          git clone ${{ github.event.inputs.repo }} test
          cd test
          rustup target add x86_64-pc-windows-gnu
          rustup toolchain install stable-x86_64-pc-windows-gnu
          sudo apt install -y mingw-w64
          cargo build --target x86_64-pc-windows-gnu -p gameserver --release
          cargo build --target x86_64-pc-windows-gnu -p sdkserver --release

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            test/target/x86_64-pc-windows-gnu/release/*.exe
          name: Build_${{ github.run_id }}
          tag_name: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
