name: Android IMG Unpack

on:
  workflow_dispatch:
    inputs:
      IMG:
        description: 'IMG直链'
        required: true
      IMGTYPE:
        description: 'IMG类型'
        required: true
        default: 'boot'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 准备
        run: |
          sudo apt update
          sudo apt install device-tree-compiler p7zip-full
          git clone https://github.com/cfig/Android_boot_image_editor work

      - name: 安裝JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: 下载img
        run: |
          curl -o ./work/${{ github.event.inputs.IMGTYPE }}.img ${{ github.event.inputs.IMG }}
          
      - name: 解包
        run: |
          cd work
          chmod +x ./gradlew
          ./gradlew unpack
          cd build/unzip_${{ github.event.inputs.IMGTYPE }}
          zip -r -9 Unpack_${{ github.event.inputs.IMGTYPE }}.zip ./*
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./work/build/unzip_${{ github.event.inputs.IMGTYPE }}/Unpack_${{ github.event.inputs.IMGTYPE }}.zip
          name: Unpack-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: Unpack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
