name: Video Downloader

on:
  workflow_dispatch:
    inputs:
      URL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install yt-dlp
        run: |
          pip install yt-dlp
          
      - name: Download Video
        run: |
          mkdir temp
          cd temp
          yt-dlp -f bestvideo+bestaudio --merge-output-format mkv --write-subs "${{ github.event.inputs.URL }}"

          
      - name: Upload 2 Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Downloaded_${{ github.run_id }}
          path: /temp
