name: Video Downloader

on:
  workflow_dispatch:
    inputs:
      URL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install yt-dlp
        run: |
          pip install yt-dlp
          
      - name: Download Video
        run: |
          mkdir temp
          cd temp
          yt-dlp -f bestvideo+bestaudio --merge-output-format mkv --write-subs "${{ github.event.inputs.URL }}"

      - name: Split Big Video
        run: |
          cd temp
          shopt -s nullglob
          for video in $(ls); do
          if [[ -f "$video" ]]; then
            size=$(du -sb "$video" | awk '{print $1}')
            if [[ "$size" -ge "$((2 * 1024 * 1024 * 1024))" ]]; then
              split -d -b 1536m -- "$video" "$video.part"
            fi
          fi
          done

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            temp/*
          name: Download_${{ github.run_id }}
          tag_name: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
